### ISSUE TITLE
PDF Export not working because one chart has a Georef Problem (EDQT)

### ISSUE THREAD

**Issue by maikst** [mipastgt/AIPBrowserDE-Public#37]
I am currently unable to export the AIP as  PDF, as EDQT is encountering a georeference problem. An error message appears every time I try.

Unfortunately, there seems to be no option to delete the problematic page and proceed with exporting the rest. At least I haven’t found a way to do so.

It would be very helpful to have a feature that allows users to remove faulty pages or, alternatively, an error-handling mechanism that skips invalid pages, shows a corresponding error message, and still exports the remaining content.

Best regards,
Maik

**Comment by mipastgt** [comment]
I cannot detect any error with EDQT. I just exported the whole AIP with the default settings without any problem.
Please follow the guidlines from here [Rückmeldungen](https://mpmediasoft.de/products/AIPBrowserDE/help/AIPBrowserDE.html#R%C3%BCckmeldungen) and tell me

* which version of the software do you use (see bottom of "settings" page)?
* what exactly did you do?
* send me the log file with the error messages as described above.

**Comment by mipastgt** [comment]
From another user I've got this screenshot:

<img width="724" height="460" alt="Image" src="https://github.com/user-attachments/assets/ac1c3a65-7f91-48ef-a252-50178ef09631" />

I'll try to see what I can do.

**Comment by mipastgt** [comment]
The cause of the problem in the data has been fixed. However, in order for the export to work again, the incorrect data in the cache must also be deleted. Unfortunately, this requires manually deleting the “aip-vfr” folder within the “.AIPBrowserDE” folder in the user directory. How to display this normally hidden folder is described here
https://mpmediasoft.de/products/AIPBrowserDE/help/AIPBrowserDE.html#R%C3%BCckmeldungen.
The next version of the software will include a self-correction feature in case a similar problem occurs again.

**Comment by fhb** [comment]
Similar issue: I already deleted the aip-vfr cache and get the following error reports with consequently missing files:

Georeference
Georeference information of page 'EDFE Frankfurt-Egelsbach 7' is inconsistent.
- Checksums differ: (page)
'debf5807b3fe05b41d6e0677a141e4df88a03796c2e2ac1412e5d69f83739b03' != (georef)
'728666e273b5d214252954c3b04651608daabffc2944fa5b8e4f70587eb9e474'.
- Page width or height differ.
Page export
Could not export selected pages from 'EDFE_Airport_Frankfurt-Egelsbach' to Users/Felix/Library/CloudStorage/Dropbox/Apps/ForeFlight/contentpack/AIP-VFR-Germany/**

**Artificial ICAO code 'ED7J' generated for aerodrome 'Locktow'.**

**Comment by mipastgt** [comment]
I am a bit lost here because I cannot reproduce the problem on my machine although another user has reported a similar problem today via email too. I've repeated the export of the AIP update from last thursday. Could you try again and let me know the outcome?

**Comment by fhb** [comment]
did delete the mentioned hidden vfr folder again and still getting the same error: 

<img width="653" height="255" alt="Image" src="https://github.com/user-attachments/assets/268e120a-0fb8-4b54-adc4-7c13b7420c68" />

[trip-kit-config-AIP-VFR-Germany-ffcp.json](https://github.com/user-attachments/files/23570515/trip-kit-config-AIP-VFR-Germany-ffcp.json)

**Comment by mipastgt** [comment]
I could finally reproduce the error. It seems the page has been rotated by the DFS. You can still see the inconsistency on their web site because the thumbnail is still wrong.

Current thumbnailpage:
<img width="474" height="101" alt="Image" src="https://github.com/user-attachments/assets/55fb1244-3069-4a55-81fd-27aa2f2a1190" />

Current page:
<img width="491" height="384" alt="Image" src="https://github.com/user-attachments/assets/e40ab4c4-69bc-48e8-b8cf-56a647664e0c" />

I hope I could fix that now.

Please delete the hidden folder and try again.

**Comment by fhb** [comment]
it's fixed. 

Only the following is still shown: 

<img width="457" height="83" alt="Image" src="https://github.com/user-attachments/assets/cdf9281b-af64-4b7d-b1b9-2de11c348351" />

**Comment by mipastgt** [comment]
OK, good to hear. Thanks for reporting the issue and doing the testing.
(The note about Locktow is just a reminder that this airfield does not have a real ICAO code.)

**Comment by mipastgt** [comment]
A preview version with a hot-fix for this issue is available here: https://mpmediasoft.de/products/AIPBrowserDE/help/AIPBrowserDE-Preview.html This fix should make it easier to recover from such inconsistencies in the future.
